platform :ios, '6.0'
pod "AFNetworking", "1.3.3"
pod 'SDWebImage'
pod 'MTLog'
pod 'UI7Kit'
pod 'HMSegmentedControl'
pod 'RegexKitLite'
pod 'SVProgressHUD', '~> 1.0'
pod 'ZAActivityBar'
pod 'JSMessagesViewController'
pod 'ALActionBlocks'
pod 'NSString+Emoji'
pod 'SDWebImage-ProgressView'
pod 'FMDB'
pod 'JDStatusBarNotification'
pod 'MCSwipeTableViewCell'
pod 'SSKeychain'
